default: clean selected

clean:
	rm -f *jpg *png

selected:
	convert -geometry 1521x2016 orig/Photo_Kiosk_cageFrame.jpg Photo_Kiosk_cageFrame.jpg
	convert -geometry 1521x2016 orig/Photo_Kiosk_fluidPumpMount.jpg Photo_Kiosk_fluidPumpMount.jpg
	convert -geometry 1521x2016 orig/Photo_Kiosk_insideView.jpg Photo_Kiosk_insideView.jpg
	convert orig/Photo_Kiosk_PelletDispenser.png Photo_Kiosk_PelletDispenser.jpg

# This is the end of the file.
